name: Deploy to Contabo VPS

on:
  push:
    branches: [ "zip-update" ]   # <- ahora escucha a tu rama zip-update

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Desplegar en VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@185.216.75.41 << 'EOF'
            cd /root/Modulo-Compra-Java || git clone git@github.com:Vayxzi/Modulo-Compra-Java.git /root/Modulo-Compra-Java
            cd /root/Modulo-Compra-Java
            git fetch origin
            git checkout zip-update
            git pull origin zip-update
            ./gradlew build -x test
          EOF
