spring:
  datasource:
    # Apunta a la base de datos que creamos en el VPS
    url: jdbc:mysql://localhost:3306/compras_vps?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: mi_app_user
    password: mi_password_segura

# --- AÑADE ESTO ---
app:
  clients:
    # Usando el puerto 8081 como indicaste
    validations: http://localhost:8081